from pinjected import injected

@injected
def config_provider(): ...
@injected
def database_connection(): ...
@injected
def user_service(): ...
@injected
def cache_service(): ...
@injected
def logger_service(): ...
@injected
def auth_config(): ...
@injected
def auth_provider(): ...
@injected
def token_service(): ...
@injected
def session_manager(): ...
@injected
def list_service(): ...
