[package]
name = "pinjected-indexer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pinjected-indexer"
path = "src/main.rs"

[dependencies]
# AST Parsing (reuse from linter)
rustpython-ast = "0.3"
rustpython-parser = "0.3"

# Async runtime
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1"

# Data structures
dashmap = "5.5"
parking_lot = "0.12"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
toml = "0.8"

# File watching
notify = "6.1"

# CLI
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utils
ahash = "0.8"
once_cell = "1.19"
dirs = "6.0.0"
ctrlc = "3.4.7"
libc = "0.2"

[dev-dependencies]
tempfile = "3.8"
pretty_assertions = "1.4"
dirs = "6.0.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
