[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[project]
name = "pinjected-niji-voice"
version = "0.1.5"
description = "Niji voice API bindings for pinjected dependency injection framework"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "proboscis", email = "nameissoap@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pinjected",
    "httpx>=0.28.1",
    "tenacity>=9.0.0",
    "pydub>=0.25.1",
    "audioop-lts; python_version >= '3.13'",
    "returns",
    "cloudpickle",
    "frozendict",
    "makefun",
    "cytoolz",
    "beartype",
    "rich",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pinjected_niji_voice"]

[tool.pytest.ini_options]
pythonpath = ["src/pinjected_niji_voice"]

[tool.uv.sources]
pinjected = { workspace = true }
injected-utils = { workspace = true }

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.1.1,<9",
]
