[package]
name = "pinjected-linter"
version = "0.1.0"
edition = "2021"
authors = ["Kento Masui <noreply@anthropic.com>"]
description = "A blazing fast linter for the Pinjected dependency injection framework"
repository = "https://github.com/pinjected/pinjected"
license = "MIT"
readme = "README.md"
keywords = ["linter", "pinjected", "static-analysis", "python"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "pinjected-linter"
path = "src/main.rs"

[dependencies]
rustpython-parser = "0.3"
rustpython-ast = "0.3"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3"
rayon = "1.7"
toml = "0.8"

[dev-dependencies]
tempfile = "3.8"