[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[project]
name = "pinjected-reviewer"
version = "0.1.0"
description = "code review utilities for pinjected library"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "proboscis", email = "nameissoap@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pinjected",
    "pytest",
    "loguru",
    "returns",
    "cloudpickle",
    "frozendict",
    "makefun",
    "cytoolz",
    "beartype",
    "rich",
    "fire",
]

[project.scripts]
pinjected-reviewer = "pinjected_reviewer.__main__:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pinjected_reviewer"]

[tool.pytest.ini_options]
pythonpath = ["src/pinjected_reviewer"]

[tool.uv.sources]
pinjected = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.1.1,<9"
]
