name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  actions: read
  pull-requests: write
  repository-projects: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version

      - name: Install dependencies
        run: |
          uv pip sync

      - name: Configure test environment
        env:
          WANDB_MODE: "disabled"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "Setting up test environment"

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          cd test
          uv run pytest -v --tb=short
