name: Sync to Proboscis Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    name: Sync main branch to proboscis/pinjected
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.PROBOSCIS_REPO_TOKEN }}"
          
      - name: Clone and push to proboscis repository
        run: |
          # Clone the current repository to a temporary directory
          TEMP_DIR=$(mktemp -d)
          cp -r . $TEMP_DIR
          
          # Navigate to the temporary directory
          cd $TEMP_DIR
          
          # Push to proboscis repository using GitHub CLI
          gh repo sync proboscis/pinjected --source CyberAgentAILab/pinjected --branch main --force
