name: Sync to Proboscis Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    name: Sync main branch to proboscis/pinjected
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to proboscis repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PROBOSCIS_REPO_TOKEN }}
          repository: proboscis/pinjected
          branch: main
          force: true
