name: Sync to Proboscis Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    name: Sync main branch to proboscis/pinjected
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Push to proboscis repository
        run: |
          # Clone the current repository to a temporary directory
          TEMP_DIR=$(mktemp -d)
          cp -r . $TEMP_DIR
          cd $TEMP_DIR
          
          # Set up remote with token and push
          git remote add proboscis https://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@github.com/proboscis/pinjected.git
          git push -f proboscis main:main
