name: Sync to Proboscis Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    name: Sync main branch to proboscis/pinjected
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup SSH deploy key
        env:
          PROBOSCIS_SSH_KEY: ${{ secrets.PROBOSCIS_SSH_KEY }}
        run: |
          # Save the SSH key to a file
          echo "$PROBOSCIS_SSH_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          # Fix newlines in the SSH key
          sed -i 's/\\n/\n/g' ~/deploy_key.pem
          
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Push to proboscis repository
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          # Clone the current repository to a temporary directory
          TEMP_DIR=$(mktemp -d)
          cp -r . $TEMP_DIR
          cd $TEMP_DIR
          
          # Set up remote with SSH and push
          git remote add proboscis git@github.com:proboscis/pinjected.git
          git push -f proboscis main:main
